### ISSUE TITLE
go-fuse: Unimplemented opcode POLL

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#430] opened 2019-10-18 17:23 UTC
Seen in Debian `buster`, which is considered stable. Any ideas?

```
Oct 18 16:28:19 lechner-desktop gocryptfs[1318]: go-fuse: Unimplemented opcode POLL
```

**Comment by lechner** [comment] 2019-10-18 17:25
Same for `INTERRUPT`.

```
Oct 18 16:32:50 lechner-desktop gocryptfs[2716]: go-fuse: Unimplemented opcode INTERRUPT
```

**Comment by madscientist42** [comment] 2019-10-23 15:24
Also getting, "Unknown opcode 2016".  Guess someone needs to check upstream on that and see if there's something off there in their code or something this project needed to know on things.

I'll do that.  I'm planning on using it for an embedded device that needs secured storage at rest.  While it's not "broken" at this time for what we're doing- it is annoying and of concern for GA on the device in question.  :-)

**Comment by mlow** [comment] 2019-10-29 23:45
Also experiencing crashing with gocryptfs 1.6.1-1+b20 on Debian buster, arm64:
https://gist.github.com/mlow/abf9d1a4e34973bb387ea380f722c97e

Steps to reproduce:

```
gocryptfs -init cipher
gocryptfs cipher clear
touch clear/hi
```

**Comment by lechner** [comment] 2019-10-30 00:02
Matt,

I am the Debian maintainer. The current version in `buster` is 1.7-2. Why are using an old version?

Kind regards,
Felix

**Comment by lechner** [comment] 2019-10-30 00:08
Sorry, I got confused. You are using `stable`. It's confusing because both code names start with a `b`, buster and bullseye.

**Comment by lechner** [comment] 2019-10-30 00:12
I do not see what you see on Debian `stable`. Here, the commands complete successfully using `1.6.1-1+b20` on top of `ext4`. What is your underlying file system, please?

**Comment by mlow** [comment] 2019-10-30 00:24
> I do not see what you see on Debian `stable`. Here, the commands complete successfully using `1.6.1-1+b20` on top of `ext4`. What is your underlying file system, please?

Also using `ext4`. I had success with gocryptfs 1.6.1 on top of ZFS, but that was on x86 (and on Archlinux). I get the same result on top of ZFS or ext4 on Debian buster arm64. To be precise, I'm using this build: buster-minimal-rock64-0.9.14-1159-arm64.img.xz from https://github.com/ayufan-rock64/linux-build/releases/tag/0.9.14

**Comment by lechner** [comment] 2019-10-30 00:39
What's wrong with this one? https://packages.debian.org/buster/armhf/gocryptfs/download

**Comment by lechner** [comment] 2019-10-30 00:47
Well, I am not sure why it matters. The golang runtime uses only `libc` from what I heard, and the build you are using has the same version of `libc` as `buster`.

One problem maybe that ARM is so highly configurable. I spent several months on porter boxes to get `golang-github-jacobsa-crypto` and `golang-github-rfjakob-eme` to build on all the varieties.

**Comment by mlow** [comment] 2019-10-30 00:58
> What's wrong with this one? https://packages.debian.org/buster/armhf/gocryptfs/download

I'm actually using https://packages.debian.org/buster/arm64/gocryptfs/download -- Sorry, to clarify, the only non-official repo I'm using is that which provides ayufan's kernel builds for the rock64.

My limited knowledge stops me from moving any further forward in understanding what the heck is going on with this. I've spent very little time working with applications written in Go and know very little about the ecosystem as a whole. I'm just hoping the info I've provided can be of some use to the people who know what they're doing in figuring this out :)

**Comment by rfjakob** [comment] 2019-10-30 08:53
A few comments

1) unknown opcode 2016 is from some kernel patch in google cloud

2) unimplemented opcode is  annoying but harmless

3) @mlow : you get crashes? That's concerning. Do you have the panic message?

**Comment by mlow** [comment] 2019-10-30 17:27
@rfjakob To clarify only gocryptfs is crashing.

A bit more info:
I can create directories in the root of the clear directory once mounted, and corresponding directories with encrypted names get created in the cipher directory. I can also create new directories within the root level directories (and deeper), but as soon as I try to list the contents of one of those directories, gocryptfs crashes with the same panic message I posted above.

When I try to create a file with `touch`, or by `echo hi > file`, gocryptfs crashes with the same panic message. However, an empty file does get created.

Occasionally, with either of the above operations, this is the panic message that is given: https://gist.github.com/mlow/1e7460050b83f3dfaa19d8dae4e56e

**Comment by rfjakob** [comment] 2019-10-30 19:04
Getting a 404 error for the link, you mean https://gist.github.com/mlow/1e7460050b83f3dfaa19d8dae4e56e44 ?

**Comment by mlow** [comment] 2019-11-01 09:30
@rfjakob That's the one! Edited my reply.

**Comment by rfjakob** [comment] 2019-12-28 23:22
Crash is on this line in go-fuse code: https://github.com/hanwen/go-fuse/blob/58dcd77a24cd3d5dd8191abd8d9e3c772578bc27/fuse/request.go#L212

This is already fixed in go-fuse via https://github.com/hanwen/go-fuse/commit/fd7328faf9fdf75709f7ba7df7072aaf4eeb18b3 (ticket https://github.com/hanwen/go-fuse/issues/276 ). However, that change does not seem to be in Debian yet.

Do you want to try a fresh arm64 build? [gocryptfs.tar.gz](https://github.com/rfjakob/gocryptfs/files/4007560/gocryptfs.tar.gz).

```
$ ./gocryptfs -version
gocryptfs v1.7.1-18-gdb43bfc without_openssl; go-fuse v2.0.2-61-g3a46380; 2019-12-29 go1.13.3 linux/arm64
```

**Comment by mlow** [comment] 2020-02-27 08:02
Finally had the chance to look at this again. The build you linked above does indeed work; rather than crashing, it prints 'Unknown opcode 2016' when running in the foreground.

**Comment by dc2** [comment] 2020-05-14 11:11
> Do you want to try a fresh arm64 build? Attached as [gocryptfs.tar.gz](https://github.com/rfjakob/gocryptfs/files/4007560/gocryptfs.tar.gz), version output:

@rfjakob Any updates on this? With the build you attached it works for me, but the recently released v1.8.0 still uses the old go-fuse v1.0.1, so I can't use it on my Odroid N2.

**Comment by rfjakob** [comment] 2020-05-15 07:24
Ok, i have to check why it does not pull the newer version.

**Comment by dc2** [comment] 2020-05-15 07:35
The current go.mod [references](https://github.com/rfjakob/gocryptfs/blob/ead7008a08f9ace4591ebbc03e63fdc7ef37e502/go.mod#L6) v1.0.1 of go-fuse so I guess that this would be the culprit? Is gocryptfs migrated to the new go-fuse API (#409) already, if so I could for now build it with a patched go.mod myself, at least for now :)

**Comment by rfjakob** [comment] 2020-05-15 07:57
Yes, then that's the reason. gocryptfs still uses the v1 api, but i think go-fuse v2 still supports the v1 api.

**Comment by rfjakob** [comment] 2020-05-17 12:27
@dc2 fixed now in master.

**Comment by dc2** [comment] 2020-05-17 14:20
Nice, thank you! :)

**Comment by rfjakob** [comment] 2021-05-05 14:42
Looks like these nuisance messages are gone in gocryptfs v2.0-beta3. gocryptfs v2.0 uses the go-fuse v2 API and the v2 API does not seem to emit them.

**Closed by rfjakob** 2021-05-05 14:42 UTC
