### ISSUE TITLE
gocryptfs keeps crashing

### ISSUE THREAD

**Issue by jsalatiel** [rfjakob/gocryptfs#48] opened 2016-10-15 19:11 UTC
@rfjakob  , i am now using gocryptfs to encrypt my home directory but i am getting lots of crashing ( transport endpoint not connected ) when doing high i/o. Actually i can easily replicate when i try use crossover ( wine manager) to install microsoft office. Any information i can provide to help debugging?  I have tried the same process in other machine and also crashed, but i haven't created a log though i think it is probably the same. 

Using gocryptfs v1.1-rc1-21-gdc78e63; go-fuse 41c29e1; 2016-10-15 go1.6.2

These are the last lines from -debug: ( if i am leaking some key , please tell me so i could recreate my encrypted folder )
```
2016/10/15 16:04:13 Dispatch 484614: WRITE, NodeId: 7487.  8192 bytes
ino3277431: FUSE Write: offset=82059264 length=8192
nonceGenerator.Get(): d0369a49e11c1d9087f3980f488b4ce7
ino3277431: Writing 4096 bytes to block #20034
nonceGenerator.Get(): 60a3314d85d0065d80b066f07e77f9c5
ino3277431: Writing 4096 bytes to block #20035
2016/10/15 16:04:13 Dispatch 484615: SETATTR, NodeId: 3826. data: {mtime 1475522697.000000000} 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x520572]

goroutine 41847 [running]:
panic(0x6cd8c0, 0xc82000e100)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/hanwen/go-fuse/fuse/nodefs.(*loopbackFile).Utimens(0xc82089fae0, 0x0, 0xc82013a140, 0x0)
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/nodefs/files_linux.go:41 +0x202
github.com/rfjakob/gocryptfs/internal/fusefrontend.(*file).Utimens(0xc820850b40, 0x0, 0xc82013a140, 0x0)
	/dev/shm/src/github.com/rfjakob/gocryptfs/internal/fusefrontend/file.go:392 +0xb4
github.com/hanwen/go-fuse/fuse/pathfs.(*pathInode).Utimens(0xc820462f00, 0x0, 0x0, 0x0, 0xc82013a140, 0xc820ede018, 0x0)
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/pathfs/pathfs.go:698 +0x1c2
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).SetAttr(0xc82005eb40, 0xc820ede000, 0xc8206aa338, 0x0)
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:251 +0x3ce
github.com/hanwen/go-fuse/fuse.doSetattr(0xc8200a00e0, 0xc8206aa240)
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/opcode.go:161 +0x54
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc8200a00e0, 0xc8206aa240, 0xc8206aa240)
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/server.go:398 +0x2ff
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc8200a00e0, 0xc820b1be01)
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/server.go:377 +0xde
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/dev/shm/src/github.com/hanwen/go-fuse/fuse/server.go:285 +0x61e
```

**Comment by jsalatiel** [comment] 2016-10-16 00:07
Another crash. This time just compiling openwrt.
Very easy to replicate:
`git clone git://github.com/openwrt/openwrt.git`
`cd openwrt ; make menuconfig # exit and save`
`make V=99 -j5`

it will crash after a while.

**Comment by rfjakob** [comment] 2016-10-16 11:07
Root cause is https://github.com/hanwen/go-fuse/pull/100 . I will add a workaround to go-fuse until https://github.com/hanwen/go-fuse/pull/131 is merged into go-fuse.

**Comment by jsalatiel** [comment] 2016-10-16 11:20
Thanks. After fixing tell me that i will test it again!

**Comment by rfjakob** [comment] 2016-10-16 13:15
Commit 5144470e3d30499fa42af84927fa8adc27b51e68 should stop the crash.

**Comment by jsalatiel** [comment] 2016-10-16 15:16
@rfjakob, the crashes really stopped, but there is something that worries me, i still can not compile openwrt inside gocryptfs mounted directory.
To make sure i have downloaded the same git revision 3 times:
First : gocryptfs
Second : tmpfs
Third: ext4
 
In all of them i just 'cd openwrt && make menuconfig', saved, and run 'make V=99 -j5'

tmpfs and ext4 compile just fine.
gocryptfs compilation fails with a very strange error about missing files.

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /usr/bin/env bash /home/jsalatiel/openwrt/build_dir/host/m4-1.4.17/build-aux/missing aclocal-1.14 -I m4
autom4te: need GNU m4 1.4 or later: /home/jsalatiel/openwrt/staging_dir/host/bin/m4
aclocal-1.14: error: echo failed with exit status: 1
Makefile:1496: recipe for target 'aclocal.m4' failed
make[4]: *** [aclocal.m4] Error 1
make[4]: Leaving directory '/home/jsalatiel/openwrt/build_dir/host/m4-1.4.17'
Makefile:28: recipe for target '/home/jsalatiel/openwrt/build_dir/host/m4-1.4.17/.built' failed
make[3]: *** [/home/jsalatiel/openwrt/build_dir/host/m4-1.4.17/.built] Error 2
make[3]: Leaving directory '/home/jsalatiel/openwrt/tools/m4'
tools/Makefile:122: recipe for target 'tools/m4/compile' failed
make[2]: *** [tools/m4/compile] Error 2

```
I think something is getting corrupted because it makes no sense since i have all dependencies there and it builds just fine outside gocryptfs :/

**Comment by rfjakob** [comment] 2016-10-16 17:46
Yes, I can reproduce this. First guess is that something is wrong with the timestamps.

**Comment by rfjakob** [comment] 2016-10-16 17:48
Oh and then there's this in the syslog, but I'm not sure if it's related:
```
Okt 16 19:48:03 brikett gocryptfs[10209]: WriteDirIV: open /var/tmp/a/j8GwQvAWQcocIxVflHOv3w==/_NTMSCstFWFmr95765jP2Q==/ZNsik5RJrKwnOueCPXZa2w==/T7fyl00XZY2NwixQjeKeEg==/IRt15pYGvmxSaWZa-vsnYA==/3ESOTv2dMsFHpeRJzl4zcA==/7jJxDbLVbK7id1t1GWEBVw==/QoP24WWU2BVMJqJbdnPutw==/w7C2TJXojTNWV3y-FYIZPw==/y4oiJX-bfQM1ZFMNZiA7Xw==/Kxirimi-sO7p3CVQ8T0dig==/J28yWZ2fl8vkIUM2joaGOQ==/XmzrpGZuSYmKIS8hYnwQDA==/D3rs_0MRztSfZ_STORS6GQ==/wLZSib14Qhu7k-y8zOzrMQ==/Effc3gs8FBQ2snf828ej5g==/9vzP3ujPZQQmCucXQwsJ6Q==/PY-wZG23Ft8z3yWUPuCEjw==/EMquUfnqGuaGxA_NHSAqPw==/9igrcV2MWqrrp0c6p6a8BA==/YzUi_AdtbancUK0-N0y6qw==/cFBvSjTWLkdTW-RsYbjoZQ==/Gj383pW-I0Uj0YGiXR7eTg==/Y-bu2wCxR4ALX5QtDLDJHg==/PlVYHulg_SNEMwO-NQp3xA==/OAXsf6uyAEr2WWi_K06b9g==/N5D5jgy2diqmOB0Jn5mflw==/nitFLZ017ERBJuYE9ddxrA==/3ZuMX0zlwrwuVlYkg2bF8w==/VaA6KMs-l4YFtbcj5gBRcw==/sMHV0hAmIU0kCFnqGhIZ1Q==/gWBJmoxluYG7q1qjeTu0lw==/s-i2vH8xpTKFEekp-DvZnQ==/975Eu0n8kc4hmtTXq7kZkQ==/DONYxo5YmoHNNOLKYNTesA==/X_hSWKsZTvH9yIx1rzmGtQ==/16xapECjDsmJVX9bX8E40Q==/KFj0u8IhFBBX7u9jEn9sEA==/9e2EsavY7ZCQ3hWmJTrBKw==/ckxXULhF5gAkQOKZPCMh5w==/xlS5ynUF8O6e3gNOVw6a_Q==/PkRiYY53eBzikBPSCGM-EA==/ddvDfHZNTqI-qdHrDFgOtg==/f-dsb8UfateueDlVtyybBA==/M_3j4wFx_hzV7FzfgqZPRw==/vKldkhABntsRngGmG7vIBA==/5nm8OnYTu36RgsqqXI34CQ==/VU3yJsdzWlVqm6b-U2RU9Q==/m1jPgXW4ZVnn3EoIZUIC7g==/PRREV8sigyQVtC7ycatRmA==/3-VWXRn-DV94s1hIour8ww==/wh-M8vB3DlS-mfebYmtm6A==/1OXAY-ErhoQJxqtWcX3q1w==/t-20FYAJvP1-kCGZ4dS09A==/um6f4pHuzAfik5--tzInRQ==/bMNXcqs1-ypgllJTZyh-gg==/b46uvpgFIOKJxppeG93qpw==/6AmCWlcZrWPfAeGVyMXoLg==/RgyLUhU7UmCM15TqNxKEnw==/aewE-f7jK6OEh4D7z9MfiQ==/cHQwNKvytIj_J7Pv-wZBrQ==/KdL6DTpoIyfINRYSRLY7rQ==/_EA8SDhhWYlwLEH3Wpphlw==/__N2cWxEjty3jX54mAywsQ==/GfonLyeds6UrrmnRMGvz_A==/xDhuVdgq-0xXCEfgBMyxsg==/6OC9tV13TDtMwwSKNB-e-A==/YT1MCUOVXiTX-PnjHvROvg==/PrSejxShrfLsS-49fDVO3w==/yhiCHYKA9uT3EWk1I436Fw==/jnPFRRDLmwnemfvZhwCqJw==/aujLsJozHeemyhQGn_tQWw==/xqy8IWCp8i7NS6-mG4BEkA==/DwyKS_Qide0gGubZu9Y8ZA==/8pjKV_sjApkXDdmOsnDrBA==/1qjovO0ckQK_711n4hS8IA==/XEzaWF_dI0xLApy0znrjkQ==/rc8RzUEat7azRulh2e4C0A==/AOFbyAALzs2V7VYkh-tJSQ==/i_I0sXuAY9QT4kyUVYEtXQ==/otnLzztjBW2ZHAN0am1ntA==/hwTNGZLMFx6rGkPtrkxSVA==/YcOZKNvGrIn8yWI6JFMqFw==/A5zEOQ8--_k_Z1F-Ew-9rA==/NnqnpQCS83pWxtJtnGzaDg==/3hCbglqXEoepyRkFFyASFw==/iPkg7ZRNZkmVvMvWZWHlew==/56NBZqVrE5ITx-EnAzNHzA==/RltSBcRP2nKa4yDcnWLPEw==/mL6Sa6VWXyRIPVCj05foUA==/rAigJTJUNdamamC6UywQLA==/4VUBAFtP03sqXbZcd3XX2w==/rEwlD4Cil51E6V_h8TiniQ==/GxDE_lvITRYaU0rAII2xFQ==/yAIzrN6wz-pD1Qe8Uh3GnA==/BUHsVyFvKAwLMio2k8BG9g==/8lT_-jSOB1d3hGkIjx058w==/OSA-WVnt5paY6Y8BUNG-RA==/pBSWUTR8NiVKz841hNp4wA==/0kWvtBAC9UFtxyAGGBglSw==/ZGBPfhKWzuEJXd--OWm93g==/w5mR02dFUdUTpb0Z6-dVLQ==/7D6hBrbvJz2-V4CyCMXr9g==/OPQQjW2o2AzHuu-CmidY2g==/hq1RIm4jHqVlSqa_eTm5VQ==/va-BUBM0ZhMBhLZpSOHM3A==/Kv8uP1h92d1N14Vr5mxTCQ==/D2fTcTmKH7UTEdQ8wW0kbA==/Fc9n7lYzMcfQYEBzwQu3Eg==/_nqr8atEZ0QOUue9GZyWWw==/Rn8tlSjJgrlcsEBzHDxbOg==/TPVQjNmhU9DwubHgUVDC3A==/eouljAh6GJbDvlJ8X57uUg==/iXGXGQ5iWiP-ma6iUru5qQ==/_ipaKfiAC1rOKkScIagPpg==/bpybq4JDSoYAcyDDV_gjiA==/eVVWPixayxWp56-2M_j_Ew==/oORY-IewuMMTcnpjng9kBQ==/YQ5J6nhQ9DK5N1ZH1iCX6Q==/AYZ24ZmUy_ORFDFxcazuCw==/yUc6LHYutescxYkKzYcu1g==/rAxnOoFNOQ6TmvINjlomHQ==/Y8xm9UaBBBsYmq3Tf_BvrA==/BcMDeZNm5POXlKUCao9SYQ==/XgVlWF_5-XE1WIY5xknpFA==/7owYdY6Msra1hCaNkEzP3g==/IKEczgAx8j00dOz8DKf1xA==/NTnJYRAnfpoPOFlVvvrxLQ==/g1_AuqRA83_AzDHCTvS5hQ==/uH18WQmENO6vWfYyDaOfaQ==/cjNz05mazUMWtbNAoVh1Kg==/c7pAMqUjK3HgsqxS7PvFGg==/FksDXxVhWCxM7rgjfL5E9g==/rRv46FtGutD9fET7DPgfGg==/BsUcyqtcTtYfgyb64pxcSQ==/n5kOPhLFo1qBIDn-P9euyQ==/E7Rki-HsSB4l4vopTgfduQ==/L0XXC-QE4gAy-_Lz_D_7Ng==/J0zhcC9RGsCzkgs7FtjyAg==/GniHaLmhBWolRAlNR5A3DA==/WFM4Y20hMTBISihQYaj5VQ==/GnoPFKJ_9jFMBo8jNgPLcA==/hm7GTXnkqwE7jp41wTTAcg==/wOgiZr71Gwc074Cpdx40mw==/qtHbmYupQr4cmerAGyFH_w==/2wRTVJaJen_sQNYC62wEOQ==/oj00gieiigv9nO_kWTcaug==/5_fA0UqPqLsn4dgt157NNA==/ZCS43R00Sz2eRsFoz8sJZg==/ODAI-5ddbJgSo4dB_eeqJg==/npg7LmbnT4W-1sA41e16IA==/3F5D-khQ3aoFAvXalm_xrw==/DX-X7URk74_z9XdvRXd4Eg==/BgzQPEBuYf38RutRTJ6LZA==/8WOmDf4oCYkg1WKS-HOw4g==/ORKSvce9ZMe8WD3TRP4dDw==/pwtPZ6KcINPd4AXTWmt_gw==/9BgQtJtyFCGuOtUeQAAYUA==/zczKgkXSnzfR-81gAH970A==/9GqDrTcYzzoVUqhXdYa6hw==/fYOYXcL9b-P-zTUuvz4dtw==/Wpwpw2WFr_kNMoGrJ_vjfg==/fNYWRemGDXNlrNu149huJA==/gocryptfs.diriv: file name too long
```

**Comment by rfjakob** [comment] 2016-10-16 17:52
Yes, the timestamps of an extracted tarball are junk, everything is set to NOW. Investigating.

**Comment by jsalatiel** [comment] 2016-10-16 17:57
just in case i have stopped my owncloud and dropbox clients instances. Timestamp problems can lead to loosing data on these.  ( i think )

**Comment by rfjakob** [comment] 2016-10-16 19:41
Workaround added as https://github.com/rfjakob/gocryptfs/commit/891a3b4c8a02edc6b7c2163bce8827a70deab285 . Good idea for safety even though this only happened in a a corner case (setting the mtime but keeping the atime as-is AND operating on a file descriptor).

**Comment by rfjakob** [comment] 2016-10-16 19:45
The openwrt compile still fails, this time due to a missing feature (`D_INO_IN_DIRENT` is not implemented):
```
tar.c:1351:5: error: 'SAVEDIR_SORT_INODE' undeclared here (not in a function)
```

**Comment by jsalatiel** [comment] 2016-10-16 19:48
I can compile openwrt outside the tree. But can i use owncloud and dropbox safely ?

**Comment by rfjakob** [comment] 2016-10-16 20:48
Yes I think so!

Just because I'm interested to understand the use cases: Do you sync decrypted files via Dropbox?

**Comment by jsalatiel** [comment] 2016-10-16 22:05
I sync just a few files to dropbox, and they are unencrypted. But now that revese mode appears to be working, i will start backing up my whole owncloud data ( a lot ) reverse encrypted to dropbox.

**Comment by jsalatiel** [comment] 2016-10-16 22:18
I have a question though:
1) Is gocryptfs immune to the audit problems showed at https://defuse.ca/audits/encfs.htm ?
2) Is there inotify support in reverse mode to make dropbox detect the changes ?
3) not sending the gocryptfs.conf to the dropbox make the files safer ? 
4) whats gocryptfs.diriv ?
5) whays the maximum file name length for encrypted files ?


btw, i was able to compile openwrt source just fine now =)

**Comment by rfjakob** [comment] 2016-10-17 06:44
1) Yes. That was one of the reasons I started gocryptfs. I tried to [improve EncFS where I could](https://github.com/vgough/encfs/commits?author=rfjakob) but ultimately thought that starting a new project was the way to go.

2) No, unfortunately not. In reverse mode, changes to the backing folder happen "behind the back" of gocryptfs.

3) Yes. gocryptfs.conf contains the master key, encrypted with your password through scrypt. Due to scrypt, brute-forcing the password will be difficult, and virtually impossible if the password is strong. But if you don't upload gocryptfs.conf there is no way to even try it.

4) There is a gocryptfs.diriv in each directory, it contains 16 random bytes. These are used to randomize the encrypted file names so that identical filenames in two directories look totally different. Check [this out](https://nuetzlich.net/gocryptfs/security/#file-names) for more details.

5) 255, like on ext4. How this works is explained [here](https://nuetzlich.net/gocryptfs/security/#long-file-name-handling) .

**Comment by jsalatiel** [comment] 2016-10-17 09:50
About the filename length, is 255 the limit for a single file name, or the whole absolute path + filename ?

**Comment by rfjakob** [comment] 2016-10-17 10:15
Single file, max path is > 1000

**Comment by rfjakob** [comment] 2016-10-19 20:43
Ok to close this?

**Closed by rfjakob** 2016-10-19 20:43 UTC
