### ISSUE TITLE
Symbolic link behaviour on reverse encrypted directories

### ISSUE THREAD

**Issue by tareks** [rfjakob/gocryptfs#129] opened 2017-07-21 09:48 UTC
I seem to be experiencing odd behavior for symbolic links created within a directory that is reverse encrypted/mounted using gocryptfs. While the symlinks (broken or not) in the source directory appear to be fine, the encrypted copy may not be accessible (sometimes not stat'able), resulting in an access error which breaks tools trying to access/mirror that directory recursively.

This is on CentOS Linux release 7.3.1611 (Core), kernel 3.10.0-514.26.1.el7.x86_64, with ext4 or xfs on the source filesystem.

Any ideas why this may be happening and if there is a way to prevent it?

Setup:
Source dir: /backup/test
Encrypted dir: /mnt/backup

Steps to reproduce:
```
# gocryptfs --reverse /backup/test /mnt/backup
# cd /backup/test
# ln -s abc 123
# stat 123
  File: ‘123’ -> ‘abc’
  Size: 3               Blocks: 0          IO Block: 4096   symbolic link
Device: fd04h/64772d    Inode: 8409622     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1001/user)   Gid: ( 1001/user)
Access: 2017-07-21 11:43:27.516000000 +0200
Modify: 2017-07-21 11:43:26.275000000 +0200
Change: 2017-07-21 11:43:26.275000000 +0200
 Birth: -
# cd /mnt/backup
# ls -l 
ls: cannot read symbolic link mQkp0jYgYyIiDTuVMTjA-Q: No such file or directory
...
lrwxrwxrwx 1 user user     47 Jul 21 11:43 mQkp0jYgYyIiDTuVMTjA-Q
...
# stat mQkp0jYgYyIiDTuVMTjA-Q
  File: ‘mQkp0jYgYyIiDTuVMTjA-Q’ -> ‘lSgaCLyEZTm075kujD__93EiuG5a693Usa53zVz1gGsi0Bo’
  Size: 47              Blocks: 0          IO Block: 4096   symbolic link
Device: 25h/37d Inode: 8409622     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1001/user)   Gid: ( 1001/user)
Access: 2017-07-21 11:43:27.516000000 +0200
Modify: 2017-07-21 11:43:26.275000000 +0200
Change: 2017-07-21 11:43:26.275000000 +0200
 Birth: -
# ls -l mQkp0jYgYyIiDTuVMTjA-Q
ls: cannot read symbolic link mQkp0jYgYyIiDTuVMTjA-Q: No such file or directory
lrwxrwxrwx 1 user user 47 Jul 21 11:43 mQkp0jYgYyIiDTuVMTjA-Q
```

**Comment by rfjakob** [comment] 2017-07-21 11:00
Thanks for the report. Looks like there is a detail missing in the symlink implementation. Thanks to the reproducer i should be able to fix this quickly (within a few days).

**Comment by rfjakob** [comment] 2017-07-21 20:21
Hmm, seems to work for me. What is your `gocryptfs -version` ?
```
$ gocryptfs -reverse a b
$ cd a
$ ln -s abc 123
$ ls -l
total 0
lrwxrwxrwx. 1 jakob jakob 3 21. Jul 22:18 123 -> abc
$ cd ../b
$ ls -l
total 4
lrwxrwxrwx. 1 jakob jakob  47 21. Jul 22:18 7V8W_GdvDC0D_PV1pa9ziA -> jO3EWgKkOACOHuo7ymZ41WYAZZsDgpijkU25vrtQv0hpi6s
-r--------. 1 jakob jakob 448 21. Jul 22:15 gocryptfs.conf
-r--r--r--. 1 jakob jakob  16 21. Jul 22:18 gocryptfs.diriv
```

**Comment by tareks** [comment] 2017-07-22 00:13
Cheers for the update.

This is on: 
`gocryptfs v1.4-18-gb256c39; go-fuse v20170619; 2017-07-01 go1.6.3`

Unfortunately it doesn't seem to consistently happen. I wonder if it has something to do with characters or file names lengths or a problem with underlying fuse library?

I'll see if i can find a test case that's always reproduceable or isolate the offending characters.

**Comment by rfjakob** [comment] 2017-10-19 20:19
I coincidentially had a CentOS 7 VM running and tried this:

```
gocryptfs -config=/tmp/usr.conf -init -reverse /usr
mkdir /tmp/usr-reverse
gocryptfs -config=/tmp/usr.conf -reverse /usr /tmp/usr-reverse
ls -lR /tmp/usr-reverse > /dev/null
```
There are 9000 symlinks in /usr acc. to `find /usr -type l` but I did not get any errors.

**Comment by rfjakob** [comment] 2018-01-16 22:05
I'll close this for now, reopen if you get this again?

**Closed by rfjakob** 2018-01-16 22:05 UTC
