### ISSUE TITLE
Under -allow_other, diriv ownership can diverge from directory

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#86] opened 2017-03-02 04:16 UTC
When transferring other people's files with rsync as root under -allow_other, diriv ownership can diverge from a directory. (Rsync probably changes the ownership in a second step.) The user cannot open such
a directory. Ownership changes to the directory should probably apply to the diriv, as well.

Read permissions for group and world should probably follow the directory too. Thank you!

**Comment by rfjakob** [comment] 2017-03-02 09:06
> diriv ownership can diverge from a directory.

Indeed

> The user cannot open such a directory.

Cannot reproduce this, seems to work fine

**Comment by lechner** [comment] 2017-03-02 17:33
Thank you for making such great software.  It works great and is super stable!

Please try this procedure ('$' is for a non-privileged user, and '#' for root):

```
$ mkdir plain
$ mkdir plain/test
$ touch plain/test/test
$ mkdir crypt decrypt
$ gocryptfs -init crypt/
$ exit
```
Now everything is owned by user. Then an administrator transfers files owned by the user.
```
# gocryptfs -allow_other crypt/ decrypt/
# rsync -vaSH plain/ decrypt/
# fusermount -u decrypt/
```
The user logs back in:
```
$ gocryptfs crypt/ decrypt/
$ ls decrypt/test
ls: cannot open directory 'decrypt/test/': Permission denied
```
It happens because ownership of the diriv is not right.
```
# ls -al decrypt/test
drwxr-xr-x 2 user user    4096 Mar  2 08:58 .
drwxr-xr-x 3 user user    4096 Mar  2 08:58 ..
-rw-r--r-- 1 user user       0 Mar  2 08:58 EZUdcKJ_w-HA_ALLy3SnAA==
-r-------- 1 root root      16 Mar  2 09:00 gocryptfs.diriv
```

**Comment by rfjakob** [comment] 2017-03-02 17:37
Ok I see. I tested with gocryptfs running as root.

Will fix!

**Comment by rfjakob** [comment] 2017-03-02 18:13
Fixed in git b2f3dbb8bd37ebca50eeb33775c980e2ca1f9053 , thanks for the report!

**Closed** 2017-03-02 18:12 UTC

**Comment by rfjakob** [comment] 2017-03-02 18:17
By the way, I'm not sure about this one, because I'm always reluctant to make permissions more open:

> Read permissions for group and world should probably follow the directory too

Unless it causes problems for you I'd prefer to keep the permission as minimal as possible.

**Comment by lechner** [comment] 2017-03-02 18:39
Thank you for the prompt fix!

Personally, I don't have a use case for group or world permissions, but anyone with those rights needs the diriv to exercise them. As far as I am concerned, the directory owner decided the risk was acceptable.

**Comment by lechner** [comment] 2017-03-02 20:13
I am not sure one can implement `-allow_other` safely. (For example, you may have to make the DirIV world-writable to allow removal of directory with the same permissions.) I would get rid of that option.

There may be a way to have `-allow_root` and perhaps even `-allow_group`. But recognizing group permissions may mean moving `gocryptfs.diriv` up a level with the same ownership and permissions as the directory. (That one I am unsure about.) At that point I would also embed the DirIV in each file. :)
