### ISSUE TITLE
transport endpoint is not connected

### ISSUE THREAD

**Issue by misery** [rfjakob/gocryptfs#109] opened 2017-05-22 21:17 UTC
I'm using gocryptfs 1.3 here on ArchLinux.
I moved every directory and files to gocryptfs some days ago.

Today I mounted it with sirikali. And tried to create a subdirectory in a subdirectory. After that the subdirectory is broken. After is tried to access it, gocryptfs bail out with the error message "transport endpoint is not connected". I need to unmount the whole mount point. After that it works ok until I try to access that broken subdirectory again.

I have those entries in my syslog.

gocryptfs[1547]: OpenDir: open /home/user/Docs/.Crypt/yW5MOdFKOubMuXyaLA9w7g/aZ-KvRJ9dtn16E3CAty12A/gocryptfs.diriv: no such file or directory

I also cannot delete the broken subdirectory in decrypted state. I needed to remove those broken subdirectory in the encrypted directory.

**Comment by rfjakob** [comment] 2017-05-22 21:23
Do you see gocryptfs_paniclog files in /tmp ? These should contain a backtrace if there was a Go panic.

**Comment by misery** [comment] 2017-05-22 21:32
There is no log file in /tmp after mounting and after the "transport endpoint..." error.

I don't know if there were a log file after a create the sub-directory as I rebooted since I create the directory. I cannot reproduce a broken sub-directory.

**Comment by mhogomchungu** [comment] 2017-05-23 04:40
SiriKali disabled the creation of the log file[1] with "-nosyslog" option.

[1] https://github.com/mhogomchungu/sirikali/blob/ef3e57720ec9f418817d14b2b106c93896e1a40d/src/siritask.cpp#L227

**Comment by rfjakob** [comment] 2017-05-23 04:54
I tried deleting the gocryptfs.diriv file from a directory, and I get this:

    $ ls foo
    ls: cannot open directory 'foo': No such file or directory

syslog:

    gocryptfs[29809]: OpenDir: open /tmp/tmp.SdzvUNeNrE/a/sQ44B5TVeZlUfjteEBLodg/gocryptfs.diriv: no such file or directory

But no crash.

**Comment by rfjakob** [comment] 2017-05-23 04:55
I'll take a look today in the evening if I see something else that could panic when reading a directory.

**Comment by rfjakob** [comment] 2017-05-23 06:57
@mhogomchungu With `-nosyslog`, the backtrace would appear on the normal output (on stderr). Do you save it anywhere?

**Comment by Nodens-** [comment] 2017-05-23 07:26
Dropping root prior to calling it should create the file with proper permissions..still it may be a better idea to move logging to /var/log.. Would be better for selinux too if something like logwatch or logrotate is trying to access logs. In /tmp you would most likely have to set custom policy or context.. Not sure what distro you're using @mhogomchungu but if you're using selinux it's quite possible that's where the permission issue came from.

**Comment by rfjakob** [comment] 2017-05-23 07:35
Oh, yes, gocryptfs exits with a fatal error if it cannot create gocryptfs_paniclog ( https://github.com/rfjakob/gocryptfs/blob/master/mount.go#L120 ). I'll downgrade this to a warning and carry on.

@Nodens- gocryptfs_paniclog is not a classical logfile. It normally stays empty, and is deleted when gocryptfs exits. Only when gocryptfs crashes the file is kept and should contain a backtrace.

**Comment by mhogomchungu** [comment] 2017-05-23 07:53
"Dropping root prior to calling it should create the file with proper permissions."

It should have but it didnt, i looked in gocryptfs code and saw that it was creating the file using go API and looked into go API to see where the bug was but i stopped shortly afterwards.

I am now using go 1.8 and i can not reproduce the problem so i think go fixed it somewhere between the version i am using now and the version i was using then(cant remember it).

I use pclinuxos and i build go and gocryptfs manually because both are not in the distro's repositories.

**Comment by rfjakob** [comment] 2017-05-23 16:04
@mhogomchungu I have downgraded paniclog failures to a warning in https://github.com/rfjakob/gocryptfs/commit/508fd9e1d64131958c86175cb8d848f730e629cf , will be released in gocryptfs v1.4.

**Comment by rfjakob** [comment] 2017-05-23 19:35
@Nodens- I reviewed the file name decryption code and found possible panics with doctored and/or unlucky inputs, all fixed in https://github.com/rfjakob/gocryptfs/commit/e827763f2e6226d9f5778d56c28270264950c0f5 .

I'll close this ticket for now, but if you see another crash (even with doctored filesystems), it would be very helpful to get the backtrace.

**Closed by rfjakob** 2017-05-23 19:35 UTC

**Comment by misery** [comment] 2017-05-23 19:40
Thank you very much. I will create a new issue and look immediately for more logs if it is broken again. :-)

**Comment by Nodens-** [comment] 2017-05-24 01:25
@rfjakob I did look for a log at that point but it did not occur to me to check /tmp. Now that I know I will certainly do so.
 I am thinking on packaging gocryptfs for Fedora (and possibly CentOS later on) so it would be nice if the backtrace was also output always on stderr regardless of the /tmp log. That way it can be pushed to systemd journal as it's standard practice.

**Comment by rfjakob** [comment] 2017-05-24 06:18
Getting the backtrace into the journal would certainly be better, but how to do that? Connect stderr to systemd-cat?

**Comment by Nodens-** [comment] 2017-05-24 07:04
As long as the filesystem is mounted in /etc/fstab (so also via mount -a etc) or via a systemd.mount or systemd.automount unit, systemd should automatically grab stderr without any further action.
 I am not 100% sure but I believe that FUSE filesystems should be also automonitored by systemd even if mounted manually via command-line. Will have to test this case.
 So as long as the backtrace is always sent to stderr along with the /tmp log, it should be fine.

**Comment by Nodens-** [comment] 2017-05-24 07:15
Doing some quick research, sys-fs-fuse-connections.mount should handle it when mounted manually

**Comment by rfjakob** [comment] 2017-05-24 07:32
I'm afraid when you mount manually the output goes to the terminal. And when that terminal window is closed, it goes nowhere at all. At least that what is it like on my Fedora development box, which is why I added the gocryptfs_paniclog thing.

Looking at [sys-fs-fuse-connections.mount](https://github.com/systemd/systemd/blob/master/units/sys-fs-fuse-connections.mount) it just seems to mount the "fusectl" filesystem.

But I'll try piping to `systemd-cat` or `logger`, this would be much better than the paniclog file.

**Comment by Nodens-** [comment] 2017-05-24 07:36
Well I have an idea about full systemd integration if you're interested, so I'll open an new enhancement issue to take it over there as it's beyond the scope of this issue.

**Comment by rfjakob** [comment] 2017-05-24 09:03
Yes please, go ahead

**Comment by rfjakob** [comment] 2017-05-24 18:04
@misery I have managed to redirect the panics to syslog, gocryptfs_paniclog is no more ( https://github.com/rfjakob/gocryptfs/commit/70c16fde4c908414f6af53c3193a89fa296ef732 )!
