### ISSUE TITLE
finer control over master key

### ISSUE THREAD

**Issue by brainchild0** [rfjakob/gocryptfs#509] opened 2020-10-05 10:38 UTC
Applications are available that scan a Btrfs volume for duplicate blocks. When found, one of the duplicates is deleted to free disk space, without affecting the files, due to the multi-tier design of the system, the same feature that makes possible lightweight, CoW file copying.

This process, called de-duplication, is beneficial even for gocryptfs volumes, but a major limitation is that either the scanned blocks must be in the same gocryptfs store, or in stores that have the same master key. Otherwise, the utility cannot identify any duplicated physical data.

For two existing stores with different master keys, it would be useful to change the master key on one store to match  that of the other. Because this effect requires transcryption of an entire store, it may be infeasible to support. 

A much simpler feature would be support the creation of a new store that  uses the same master key as an existing store (for which the password is given). 

Then duplicate files entered into the second store would also be physical duplicates, and able to benefit from the de-duplication utilities.

**Comment by rfjakob** [comment] 2020-10-06 10:55
Duplicate of https://github.com/rfjakob/gocryptfs/issues/510

**Closed by rfjakob** 2020-10-06 10:55 UTC
