### ISSUE TITLE
gocryptfs-on-sshfs performance regression in v1.7

### ISSUE THREAD

**Issue by lxp** [rfjakob/gocryptfs#410] opened 2019-08-10 15:59 UTC
The changes in version 1.7 have a 10x performance penalty in my use cases.
For example, a `git status` on a remotely mounted SSHFS with gocryptfs on top of it:

With gocryptfs v1.6.1:
```
$ time git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

real	0m4,035s
user	0m0,006s
sys	0m0,014s
```
With gocryptfs v1.7:
```
$ time git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

real	0m45,383s
user	0m0,011s
sys	0m0,020s
```

**Comment by rfjakob** [comment] 2019-08-14 20:11
I can reproduce this to some degree, but it probably depends on the repo. I tested with the gocryptfs git repo:

* v1.7: 98s
* v1.6.1: 31s

3 x slowdown, probably due to the symlink-safe path walking that was introduced in v1.7. I'll what I can do.

**Comment by rfjakob** [comment] 2019-08-14 20:26
`strace -c -f -w -p PID` stats:

v1.7:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 57.31  490.108798       24515     19992       192 futex
 29.66  253.644485       81374      3117           read
  5.57   47.604868         182    261185           nanosleep
  5.14   43.984753       11639      3779           openat
  1.33   11.353190        6494      1748        52 newfstatat
  0.44    3.725286       22174       168           getdents64
  0.17    1.467871       20969        70           readlinkat
  0.15    1.255218      627609         2         1 restart_syscall
  0.12    0.999049        9990       100           pread64
  0.05    0.388523          48      8054           epoll_pwait
  0.04    0.384134          74      5174           close
  0.01    0.114774          60      1909           fcntl
  0.01    0.066398          63      1052           sched_yield
```

v1.6.1:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 52.01  145.058786       26640      5445        48 futex
 31.85   88.819323       68533      1296           read
  4.72   13.154882         182     72032           nanosleep
  3.76   10.496384       10073      1042        43 lstat
  3.06    8.527551       21698       393           openat
  2.58    7.182807     7182807         1           restart_syscall
  1.28    3.562060       21202       168           getdents64
  0.39    1.088723       10887       100           pread64
  0.26    0.735357       10505        70           readlinkat
  0.03    0.083738          38      2200           epoll_pwait
  0.02    0.044204          48       916           write
  0.01    0.032569          78       414           close
  0.01    0.030764          56       547           newfstatat
  0.01    0.023915          38       620         2 epoll_ctl
  0.01    0.023913       23912         1           unlinkat
  0.01    0.014288          20       706           fcntl
```

**Comment by rfjakob** [comment] 2020-02-26 21:30
The difference are the 3779 `openat` calls that cost us 43 seconds. This is the symlink-safe path walking.

The number 3779 is interesting as the gocryptfs repo only contains 1137 files, so making three times as many `openat` calls seems a little excessive.

**Comment by gerroon** [comment] 2020-05-14 02:55
Hi

I am in the same situation, are there  any recommendations to speed up SSHFS mounts activity?

**Comment by rfjakob** [comment] 2020-05-17 17:51
Not at the moment, sorry. If you don't use plaintextnames, you can go back to v1.6.1. The symlink race attacks don't work when symlinks are encrypted.

**Comment by rfjakob** [comment] 2020-05-17 19:43
I just pushed a change that gives me a 4x speedup by making the cache more effective. Not yet as fast as v1.6.1, but should be more usable now.

**Comment by rfjakob** [comment] 2021-05-05 14:34
I will close this in favor of https://github.com/rfjakob/gocryptfs/issues/481

**Closed by rfjakob** 2021-05-05 14:34 UTC
Labels: performance
