### ISSUE TITLE
Group permissions: No write access

### ISSUE THREAD

**Issue by xelra** [rfjakob/gocryptfs#394] opened 2019-04-15 00:53 UTC
I believe something changed recently with group permissions. I cannot tell exactly when, but I have an automated workflow that broke and I just noticed it.

I have apps and scripts that all have different users and they write to my gocryptfs mount with a shared group.
These users have lost access to all parts of the mount that they don't own anymore. They still can write to directories that they're the owner, but not to directories that they don't own and only have group access to.

I've tested the workflow manually. For the user `script1` and the group `crypto`, I logged in as `script1`. `script1` is part of the group `crypto`. Then I created a directory `test` with owner and group `crypto:crypto`. I changed the permissions to `770`. I then tried `touch x` inside the directory.
I did this inside of the gocryptfs mount and on local storage outside of the gocryptfs mount. Only on the gocryptfs mount `touch x` failed with the message `touch: cannot touch 'x': Permission denied`.

My last update could be a few months back. So I can't give a narrow timeframe when the issue appeared.

**Comment by rfjakob** [comment] 2019-04-15 07:02
Thanks for the report. A few questions to help reproduce:
* What command line do you use to mount? Just -allow_other ?
* gocryptfs version?
* Kernel version?

**Comment by xelra** [comment] 2019-04-15 08:04
Thank you for doing such a great job with gocryptfs and responding to issues so fast.
I have found some additional information that should help debug this problem.

I'm a Arch Linux user. Currently I'm on `5.0.7-arch1-1-ARCH`. I am only using the `-allow_other` option.

I was going through pacman's cache and the previous version I had installed was `gocryptfs-1.6.1-1-x86_64.pkg.tar.xz`. Yesterday I upgraded to `gocryptfs-1.7-2-x86_64.pkg.tar.xz` and saw the issue.

I've downgraded to `1.6.1` again and the issue is gone. So I believe it was introduced with version `1.7`.

**Comment by rfjakob** [comment] 2019-04-17 20:13
v1.7 reworked a lot of the permission handling to make it safe against symlink races, looks like we introduced a bug here.

**Comment by rfjakob** [comment] 2019-04-30 21:00
I can reproduce the problem.

@slackner we have a problem here. We don't take supplementary groups the calling process has into account. The problem is exactly as described here: https://unix.stackexchange.com/a/118790/45823

**Comment by slackner** [comment] 2019-04-30 23:44
That sounds indeed like a major issue. Unfortunately it does not seem that easy to fix, at least without introducing additional overhead.

I was wondering how other FUSE file systems solve that, and found "disorderfs", which apparently can correctly deal with supplementary groups. Source code is available at:
http://http.debian.net/debian/pool/main/d/disorderfs/disorderfs_0.5.6.orig.tar.bz2

Their code contains a similar block of code to drop privileges, with one addition: They use `fuse_getgroups` to query for the list of supplementary group IDs for the current request, and pass that to `thread_setgroups()`.

Documentation for `fuse_getgroups`:
https://libfuse.github.io/doxygen/fuse_8h.html#a04273db088e57d8242caa388193b6958

The low-level code to get the supplementary groups can be found here, and it does not look very nice:
https://libfuse.github.io/doxygen/fuse__lowlevel_8c_source.html#l02974 - Yes, they really use `/proc/PID/task/PID/status` to query the list of groups.

Should we port that function (either to `go-fuse` or `gocryptfs`)? Or can we come up with a better way to fix that use-case without reintroducing the race-conditions?

**Comment by slackner** [comment] 2019-04-30 23:57
GlusterFS apparently uses the same tricks, see:
https://docs.gluster.org/en/latest/Administrator%20Guide/Handling-of-users-with-many-groups/

> Group limit with FUSE
>
> The FUSE client gets the groups of the process that does the I/O by reading the information from /proc/$pid/status. This file only contains up to 32 groups. If client-side xlators rely on all groups of a process/user (like posix-acl), these 32 groups could limit functionality.
>
> For that reason a mount option has been added. With the resolve-gids mount option, the FUSE client calls the POSIX getgrouplist() function instead of reading /proc/$pid/status.

**Comment by slackner** [comment] 2019-05-01 00:42
Hacky patch that demonstrates how to fix it: http://ix.io/1HHz - With those changes, everything works again as expected for me. For macOS, we should probably check if a similar fix is required.

**Comment by rfjakob** [comment] 2019-05-01 10:10
Thanks for the analysis, most helpful! I think we should follow libfuse und gluserfs and do the same. Your patch does not look too hacky at all. Mind to post an actual `git format-patch` patch?

**Comment by rfjakob** [comment] 2019-05-01 11:15
@slackner what do you think about using a `asUser` or `runAsUser` wrapper in syscallcompat, like here?

https://github.com/rfjakob/gocryptfs/blob/96935e16b9167dc3c472505872b3fc5235203a05/tests/root_test/root_test.go#L12

**Comment by slackner** [comment] 2019-05-01 11:21
Here the same patch with `git format-patch` header: http://ix.io/1HJr - The idea to simplify the code by using an `asUser` wrapper sounds good, feel free to change the patch accordingly.

Some other changes, you might want to consider before apply it:
* Should we really read the whole file, or does a buffered reader make more sense (when can abort after reading the groups)
* Is there a better way to read the list of groups? How should we treat parsing failures? etc.

**Comment by slackner** [comment] 2019-05-01 11:22
While you are at it, maybe also add the missing `groups` to the patch subject. Ooops. ;)

**Comment by rfjakob** [comment] 2019-05-01 16:45
Merged to master, thanks!

> Should we really read the whole file

I think the kernel generates the whole file anyway, so the difference will be some CPU cycles we spend splitting the lines. I think it's good enough unless we actually see a slowdown.

> Is there a better way to read the list of groups? How should we treat parsing failures? etc.

I think there is no other way than `/proc/%d/task/%d/status`. We could use a bit of log output on errors (when proc is not mounted, for example), but otherwise, there's not much we can do when we cannot read the groups. Then we just won't set any.

I'll close this, as the bug is fixed!

**Closed by rfjakob** 2019-05-01 16:45 UTC
Labels: bug

**Comment by slackner** [comment] 2019-05-01 16:51
No problem. Did you drop the idea to add an `asUser` helper function, or did you want to do those changes separately?

**Comment by rfjakob** [comment] 2019-05-01 17:00
I still want the asUser helper, but I wanted to get the fix in first. The problem is that OpenatUser returns (int, error), while the others return just (error), and I don't know how to wrap this the best way.

**Comment by slackner** [comment] 2019-05-01 17:13
I was thinking about using just a single `(error)` return value. The file descriptor can be returned by setting `fd` (the return variable in the parent context) directly from the callback function. Not sure if that is the best way though.

**Comment by rfjakob** [comment] 2019-05-01 17:22
Good idea. Or no return value at all?

**Comment by slackner** [comment] 2019-05-01 17:23
That might be a bit difficult. We might still want to catch errors when impersonating a user fails.

**Comment by thilo-fischer** [comment] 2019-05-08 23:22
I also had issues with group permissions, at first the "permission denied" issue xelra describes. I went back from v1.7 to v1.6.1. There I had an issue with the SGID flag not being handled properly. The following script reproduces the issue:
`
gocryptfs -version
mkdir cipher plain
gocryptfs -extpass "echo foo" -init cipher
sudo gocryptfs -extpass "echo foo" -allow_other cipher/ plain/
mkdir reference
mkdir {plain,reference}/subdir
chmod g+ws {plain,reference}/subdir
chown $(whoami):$(groups | awk '{print $2}') {plain,reference}/subdir
ls -ld {plain,reference}/subdir
touch {plain,reference}/subdir/testfile
ls -l {plain,reference}/subdir/testfile

# cleanup
fusermount -u plain
rm -rf cipher/ plain/ reference/
`
testfile should have the same group ownership in plain and in reference, but had wrong group ownership in plain with v1.6.1.

However, when I use the latest version of gocryptfs (cf99cfd) that includes the bugfix discussed here for the "permission denied" issue the SGID is handled properly. Think I found a bug here, but is is already fixed with the patch discussed above.
As I spent some time investigating the issue and created the script to reproduce it, I just wanted to share this information with you ;)
