### ISSUE TITLE
File name length problem

### ISSUE THREAD

**Issue by BrsyRockSs** [rfjakob/gocryptfs#603] opened 2021-09-16 03:39 UTC
Hello, I also encountered a similar situation, I will describe the problem I encountered
English is not my native language, I try to use google translation to express my meaning, sorry

WIN10
cppcryptfs
OneDrive

I use OneDrive to back up encrypted files. In most cases, it’s great. Today，I suddenly encountered the following error
What is written in the picture is:
The path is too long to synchronize this item. Please shorten it by 165 characters and try again, or set onedrive to synchronize at a location with a shorter path.
I found the source file and put the path and file name together, the total number of characters at the end is 394
![image](https://user-images.githubusercontent.com/46119880/133541325-6bc5efde-c394-4c88-851f-862dd32d564b.png)

//===
I don’t know much about encryption algorithms and processes. I just make some suggestions and requests based on my own ideas. I hope you don’t mind.
1.
>Can you provide an option to store the file name in the form of a tree or a form similar to gocryptfs.diriv to achieve the purpose of reducing the file name,
2.
>Can some files be encrypted and some files are not encrypted? This is a useful function I found when using boxcryptor. Sometimes there are several different folders and some files under the same big encrypted root directory. The folder does not want to be encrypted, and some folders need to be encrypted. At this time, you do not need to create a new encrypted directory separately. You only need to select some folders for encryption. The folder mount point function provided by cppcryptfs can be similar. However, it is too complicated. If there are 10 files to be encrypted separately under one file, you need to create 10 encrypted directories and 10 load points to load them separately.
3.
>Regarding the file name encryption part, here is the part 2 above, whether you can choose whether to encrypt the name of the folder when encrypting the file.
Sometimes only the name of the file needs to be encrypted, the name of the folder is irrelevant or it needs to be used to find and locate the file when the file is encrypted.

//===
I have a folder in which my commonly used tools are sorted and organized, similar to the following
001-System Maintenance Tool
002-Image editing tool
003-Compression Tool
004-Video editing tool
These folders are put together in a folder named "software library", I only want these 001, 002. . . The contents of the folder are encrypted, some file names are encrypted, and some are not encrypted.
According to the current solution provided by cppcryptfs, how many such folders I have, I need to create as many encrypted directories with the same name, and then mount them separately, which is a bit too complicated.
I may need to bring up some questions from cppcryptfs, but I don't quite understand it, so I told them all at once.
I just talked about some of my feelings when I used it. There may be some stupid problems, please forgive me.
Sorry again for my English.
thanks

**Comment by page-down** [comment] 2021-09-16 05:07
Duplicate of #499

**Closed** 2021-10-03 02:44 UTC
