### ISSUE TITLE
Behavior different from ext4 and tmpfs under fakeroot

### ISSUE THREAD

**Issue by lechner** [rfjakob/gocryptfs#87] opened 2017-03-06 22:43 UTC
Hi, could 'fakeroot' behave differently on gocryptfs? A Debian package builds here using 'debuild' on both ext4 and tmpfs, but not on gocryptfs. (The error is a libtool complaint that a file referenced via a symbolic link does not exist, but it does.) Thank you!

**Comment by rfjakob** [comment] 2017-03-06 23:23
I have seen the OpenWRT build system fail, because it looked at an obscure filesystem feature (`D_INO_IN_DIRENT`), details: https://github.com/rfjakob/gocryptfs/issues/48#issuecomment-254069547

But your problem sounds like something (gocryptfs? fakeroot?) dereferences the symlink incorrectly. Do you have a reproducer for me?

**Comment by lechner** [comment] 2017-03-06 23:55
Please don't go on a goose chase. This looks like an interaction with nfs4. The following procedure works on (1) straight nfs4, (2) gocryptfs on ext4, (3) gocryptfs on tmpfs, (4) straight ext4 and (5) straight tmpfs, but fails consistently (10x plus) on gocryptfs on top of kerberized nfs4. Here it is:

Please try to build [this package from Mentors](https://mentors.debian.net/package/libpam-mount) on Debian testing. Run `debuild -S` first. A subsequent `debuild -b` fails with the error below. Thank you!

```
libtool: relink: gcc -shared  -fPIC -DPIC  .libs/pam_mount_la-misc.o .libs/pam_mount_la-mount.o .libs/pam_mount_la-pam_mount.o .libs/pam_mount_la-rdconf1.o .libs/pam_mount_la-rdconf2.o .libs/pam_mount_la-spawn.o   -L/home/lechner/Projects/PAM/libpam-mount-2.16/debian/libpam-mount/lib -L/lib -lcryptmount -lpam -lHX -lmount -lpcre -lxml2  -g -O2 -fstack-protector-strong -Wl,-z -Wl,relro -Wl,-z -Wl,now   -Wl,-soname -Wl,pam_mount.so -o .libs/pam_mount.so
/usr/bin/ld: cannot find -lcryptmount
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'pam_mount.la' with the above command before installing it
Makefile:573: recipe for target 'install-moduleLTLIBRARIES' failed
make[4]: *** [install-moduleLTLIBRARIES] Error 1
```

**Comment by rfjakob** [comment] 2018-03-28 16:54
Cannot reproduce on Debian 9 with 
```
# gocryptfs -version
gocryptfs v1.4.4 without_openssl; go-fuse v20170619-31-ga9ddcb8; 2018-03-18 go1.10
```
Mounted like this
```
# mount
192.168.122.155:/j1 on /mnt/j1 type nfs4 (rw,relatime,vers=4.2,rsize=32768,wsize=32768,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.122.154,local_lock=none,addr=192.168.122.155)
/mnt/j1/a on /mnt/j1/b type fuse.gocryptfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,max_read=131072)
```
Debuild:
```
jakob@d2:/mnt/j1/b/libpam-mount$ debuild -b
 dpkg-buildpackage -rfakeroot -us -uc -b
dpkg-buildpackage: info: source package libpam-mount
dpkg-buildpackage: info: source version 2.16-3
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Jochen Sprickerhof <jspricke@debian.org>
 dpkg-source --before-build libpam-mount
dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: applying 003-hurd-path-max-define
dpkg-source: info: applying 004-allow-usernames-beginning-with-numbers
[...]
dpkg-source: info: unapplying 009-manpage-typos
dpkg-source: info: unapplying 008-disallow-luserconf-path
dpkg-source: info: unapplying 007-fix-mount-crypt-fork-bomb
dpkg-source: info: unapplying 006-pmvarrun-allow-eacces
dpkg-source: info: unapplying 005-debian-manpages
dpkg-source: info: unapplying 004-allow-usernames-beginning-with-numbers
dpkg-source: info: unapplying 003-hurd-path-max-define
dpkg-buildpackage: info: binary-only upload (no source included)
Now running lintian...
N: 2 tags overridden (2 warnings)
Finished running lintian.
Now signing changes and any dsc files...
 signfile buildinfo libpam-mount_2.16-3_amd64.buildinfo 6C7B48C83BF32663FBAFA7F68941FDE6B5C00C5C

 fixup_changes buildinfo libpam-mount_2.16-3_amd64.buildinfo libpam-mount_2.16-3_amd64.changes
 signfile changes libpam-mount_2.16-3_amd64.changes 6C7B48C83BF32663FBAFA7F68941FDE6B5C00C5C

Successfully signed buildinfo, changes files
```

**Comment by rfjakob** [comment] 2018-03-28 16:58
Seems to work OK with Debian-packaged gocryptfs as well
```
# apt-cache policy gocryptfs
gocryptfs:
  Installed: 1.2-2+b1
```
Maybe related to kernel version? I'm on
```
Linux d2 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
```

**Comment by rfjakob** [comment] 2018-03-28 17:01
Maybe also related to NFS server kernel version?

But I guess you are right about the goose chase, seems you need a quite specific setup to hit this.

I'd say close this for now, and let's revisit it when it annoys you again?

**Closed by rfjakob** 2018-03-28 17:01 UTC
